import { emitEntityEventsFile, emitIndexEventsFile } from "../src/generator/emitter.js";

describe("emitter", () => {
  describe("emitEntityEventsFile", () => {
    it("generates with unknown context when no contextType", () => {
      const code = emitEntityEventsFile("User", "user", undefined);
      expect(code).toContain("// Generated by eventify-openapi - do not edit");
      expect(code).toContain("import { User, UserSchema } from '@api/user';");
      expect(code).toContain("import { Events, createEntityEvents } from 'eventify-openapi';");
      expect(code).not.toContain("import type");
      expect(code).toContain("createEntityEvents<unknown, User>(UserSchema)");
      expect(code).toContain(`(Events as unknown as Record<string, unknown>).User = UserEvents;`);
      expect(code).toContain("interface EventifyOpenApiEvents");
      expect(code).toContain("User: typeof UserEvents;");
      // 6 base events documented
      expect(code).toContain("BeforeCreate: TypedEvent<[unknown, User], User>");
      expect(code).toContain("BeforeUpdate: TypedEvent<[unknown, User, User], User>");
      expect(code).toContain("AfterDelete: TypedEvent<[unknown, User], User>");
      // warning
      expect(code).toContain("Changes will be overwritten");
      expect(code).toContain("user.custom.events.ts");
    });

    it("generates with custom context import", () => {
      const code = emitEntityEventsFile("Product", "product", { from: "./ctx.js", name: "SessionCtx" });
      expect(code).toContain(`import type { SessionCtx } from './ctx.js';`);
      expect(code).toContain("createEntityEvents<SessionCtx, Product>(ProductSchema)");
      expect(code).toContain("TypedEvent<[SessionCtx, Product], Product>");
      expect(code).toContain("TypedEvent<[SessionCtx, Product, Product], Product>");
      expect(code).toContain(`import { Product, ProductSchema } from '@api/product';`);
    });

    it("handles lowerName with original casing in comment", () => {
      const code = emitEntityEventsFile("ProductCategory", "productcategory", undefined);
      expect(code).toContain("productcategory.custom.events.ts");
      expect(code).toContain(`from '@api/productcategory'`);
    });

    it("handles context with different path", () => {
      const code = emitEntityEventsFile("Order", "order", { from: "@app/context", name: "AppCtx" });
      expect(code).toContain(`from '@app/context'`);
      expect(code).toContain("AppCtx");
    });

    it("always includes global augmentation", () => {
      const code = emitEntityEventsFile("Foo", "foo", undefined);
      expect(code).toMatch(/declare global\s*\{/);
      expect(code).toMatch(/interface EventifyOpenApiEvents/);
    });

    it("matches snapshot for user", () => {
      const code = emitEntityEventsFile("User", "user", { from: "./ctx.js", name: "SessionCtx" });
      expect(code).toMatchSnapshot();
    });
  });

  describe("emitIndexEventsFile", () => {
    it("handles empty array", () => {
      const code = emitIndexEventsFile([]);
      expect(code).toContain("do not edit");
      expect(code).toContain("import '@api/index.events'");
      expect(code).toContain("export {};");
      // no import lines
      expect(code).not.toContain("import './");
    });

    it("generates imports with .js extension", () => {
      const code = emitIndexEventsFile(["user", "product"]);
      expect(code).toContain(`import './user.events.js';`);
      expect(code).toContain(`import './product.events.js';`);
      expect(code).toContain("do not edit");
    });

    it("preserves order", () => {
      const code = emitIndexEventsFile(["a", "b", "c"]);
      const idxA = code.indexOf("a.events.js");
      const idxB = code.indexOf("b.events.js");
      const idxC = code.indexOf("c.events.js");
      expect(idxA).toBeLessThan(idxB);
      expect(idxB).toBeLessThan(idxC);
    });

    it("snapshot", () => {
      expect(emitIndexEventsFile(["user", "product", "order"])).toMatchSnapshot();
    });
  });
});
