import { toPascalCase } from "../utils/casing.js";

/**
 * Configuration options specifying context type imports for event emission.
 */
export type EmitterContextType = { from: string; name: string } | undefined;

/**
 * Generates TypeScript source code for a specific entity's event registration file.
 *
 * Produces a self-registering event module that initializes standard lifecycle events 
 * (`BeforeCreate`, `AfterCreate`, etc.) for an OpenAPI schema, attaches them to the 
 * global `Events` registry, and augments `EventifyOpenApiEvents` for type safety.
 *
 * @param pascalName - The PascalCase entity name (e.g., `"UserProfile"`).
 * @param lowerName - The lower-case or kebab-case entity identifier (e.g., `"user-profile"`).
 * @param contextType - Optional context import metadata specifying module path and type name.
 * 
 * @returns The formatted TypeScript file contents as a string.
 *
 * @example
 * ```ts
 * const code = emitEntityEventsFile("User", "user", { name: "AppContext", from: "./context.js" });
 * ```
 */
export function emitEntityEventsFile(
    pascalName: string,
    lowerName: string,
    contextType: EmitterContextType,
): string {
    const hasCtx = !!contextType;
    const ctxImport = hasCtx ? `import type { ${contextType!.name} } from '${contextType!.from}';\n` : "";
    const ctxGeneric = hasCtx ? contextType!.name : "unknown";

    return `// Generated by eventify-openapi - do not edit. Changes will be overwritten.
// For custom events create a separate file e.g. ${lowerName}.custom.events.ts and follow:
//   import { Events } from 'eventify-openapi';
//   Events.${pascalName}.MyCustomEvent = new TypedEvent<[${ctxGeneric}, ${pascalName}], ${pascalName}>();

import { ${pascalName}, ${pascalName}Schema } from '@api/${lowerName}';
import { Events, createEntityEvents } from 'eventify-openapi';
${ctxImport}
// 6 base events are created with correct signatures:
// - BeforeCreate: TypedEvent<[${ctxGeneric}, ${pascalName}], ${pascalName}> (ctx, entity) => ${pascalName}
// - AfterCreate: TypedEvent<[${ctxGeneric}, ${pascalName}], ${pascalName}> (ctx, entity) => ${pascalName}
// - BeforeUpdate: TypedEvent<[${ctxGeneric}, ${pascalName}, ${pascalName}], ${pascalName}> (ctx, before, after) => ${pascalName}
// - AfterUpdate: TypedEvent<[${ctxGeneric}, ${pascalName}, ${pascalName}], ${pascalName}> (ctx, before, after) => ${pascalName}
// - BeforeDelete: TypedEvent<[${ctxGeneric}, ${pascalName}], ${pascalName}> (ctx, entity) => ${pascalName}
// - AfterDelete: TypedEvent<[${ctxGeneric}, ${pascalName}], ${pascalName}> (ctx, entity) => ${pascalName}
export const ${pascalName}Events = createEntityEvents<${ctxGeneric}, ${pascalName}>(${pascalName}Schema);

(Events as unknown as Record<string, unknown>).${pascalName} = ${pascalName}Events;

declare global {
  interface EventifyOpenApiEvents {
    ${pascalName}: typeof ${pascalName}Events;
  }
}
`;
}

/**
 * Generates a barrel module that automatically registers all entity events on application startup.
 *
 * Produces side-effect imports for each generated entity event file, ensuring all event 
 * definitions and global type declarations load in the runtime registry.
 *
 * @param lowerNames - List of entity file identifiers (e.g., `["user", "order", "product"]`).
 * 
 * @returns The formatted TypeScript barrel file contents as a string.
 *
 * @example
 * ```ts
 * const indexCode = emitIndexEventsFile(["user", "product"]);
 * ```
 */
export function emitIndexEventsFile(lowerNames: string[]): string {
    const imports = lowerNames.map((n) => `import './${n}.events.js';`).join("\n");
    return `// Generated by eventify-openapi - do not edit. Changes will be overwritten.
// Barrel file - import this once at startup to register all entity events.
//   import '@api/index.events';

${imports}
export {};
`;
}